// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221121082536_EngageMigration")]
    partial class EngageMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.ClauseLeft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Clause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clause Left");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clause = "A"
                        },
                        new
                        {
                            Id = 2,
                            Clause = "B"
                        },
                        new
                        {
                            Id = 3,
                            Clause = "C"
                        },
                        new
                        {
                            Id = 4,
                            Clause = "D"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClauseRight", b =>
                {
                    b.Property<int>("ClauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClauseId"), 1L, 1);

                    b.Property<string>("Clause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClauseId");

                    b.ToTable("Clause Right");
                });

            modelBuilder.Entity("Domain.Entities.ClauseText", b =>
                {
                    b.Property<int>("ClauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClauseId"), 1L, 1);

                    b.Property<string>("ClauseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClauseId");

                    b.ToTable("Clause Text");
                });
#pragma warning restore 612, 618
        }
    }
}
